version: '3.8'

x-google:
  project: 'forge-gradle'
  service: 'forge-gradle'
  location: 'us-central1'
  network: 'forge-gradle'
  subnetwork: 'forge-gradle'
  allow_unauthenticated: true
  disable_implicit_annotations: true

services:
  gradle:
    image: openjdk:21-jdk
    environment:
      - CI=${CI:-}
    volumes:
      - ~/.gradle/caches/modules-2:/root/.gradle/caches/modules-2:z
      - ~/.gradle/caches/forge_gradle:/root/.gradle/caches/forge_gradle:z
      - ~/.gradle/wrapper/dists:/root/.gradle/wrapper/dists:z
      - ./:/opt/build:Z
    working_dir: /opt/build
    command: bash -c 'set -x
      && ./gradlew --no-daemon -p buildSrc build
      && ./gradlew --no-daemon -p buildSrc clean
      && ./gradlew --no-daemon --no-build-cache clean build'
